server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

cloud:
  aws:
    s3:
      bucketname: tanda-myblog
    credentials:
      access-key: access-key
      secret-key: secret-key
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    converters: # 추가 =========================
      preferred-json-mapper: gson
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Seoul
    username: tanda
    password: asdf0120
    
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #show-sql: true
    properties:
      '[hibernate.format_sql]': true
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1073034127006-8qphiho6idvad3emirrhpk5ub9vel31o.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          
          naver:
            client-id: _mUdbGM4OHX8tHKHW12G
            client-secret: aWxww74VBj
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            
          kakao:
            client-id: affae21c67ac05956d97510b5fef357c
            client-secret: n5onoaPTLi3epaFS4DhpawSM7jVcsIYh
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          
